In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

In [2]:
data = {'date': ['2018-01-01', '2018-02-01',
'2018-03-01', '2018-04-01',
'2018-05-01', '2018-06-01',
'2018-01-01', '2018-02-01',
'2018-03-01', '2018-04-01',
'2018-05-01', '2018-06-01'],
'visitors': [35, 30, 82, 26,
83, 46, 40, 57, 95, 57, 87, 42]}


In [4]:
df=pd.DataFrame(data,columns=['date','visitors'])

In [5]:
df.head()

date  visitors
0  2018-01-01        35
1  2018-02-01        30
2  2018-03-01        82
3  2018-04-01        26
4  2018-05-01        83

In [7]:
df.dtypes

date        object
visitors     int64
dtype: object

In [8]:
df['date']=pd.to_datetime(df['date'])

In [9]:
df.set_index('date',inplace=True)
df.sort_index(inplace=True)

In [10]:
df.head()

visitors
date                
2018-01-01        35
2018-01-01        40
2018-02-01        30
2018-02-01        57
2018-03-01        82

In [11]:
df.tail()

visitors
date                
2018-04-01        57
2018-05-01        83
2018-05-01        87
2018-06-01        46
2018-06-01        42

In [14]:
df[datetime(2018,3,1):]

visitors
date                
2018-03-01        82
2018-03-01        95
2018-04-01        26
2018-04-01        57
2018-05-01        83
2018-05-01        87
2018-06-01        46
2018-06-01        42

In [18]:
df.truncate(after="2018-03-01")

visitors
date                
2018-01-01        35
2018-01-01        40
2018-02-01        30
2018-02-01        57
2018-03-01        82
2018-03-01        95

In [19]:
df.groupby('date').count()

visitors
date                
2018-01-01         2
2018-02-01         2
2018-03-01         2
2018-04-01         2
2018-05-01         2
2018-06-01         2

In [20]:
df.resample('M').mean()

visitors
date                
2018-01-31      37.5
2018-02-28      43.5
2018-03-31      88.5
2018-04-30      41.5
2018-05-31      85.0
2018-06-30      44.0

In [21]:
df.resample('M').sum()

visitors
date                
2018-01-31        75
2018-02-28        87
2018-03-31       177
2018-04-30        83
2018-05-31       170
2018-06-30        88

In [22]:
df.groupby('date').describe()

visitors                                                 
              count  mean        std   min    25%   50%    75%   max
date                                                                
2018-01-01      2.0  37.5   3.535534  35.0  36.25  37.5  38.75  40.0
2018-02-01      2.0  43.5  19.091883  30.0  36.75  43.5  50.25  57.0
2018-03-01      2.0  88.5   9.192388  82.0  85.25  88.5  91.75  95.0
2018-04-01      2.0  41.5  21.920310  26.0  33.75  41.5  49.25  57.0
2018-05-01      2.0  85.0   2.828427  83.0  84.00  85.0  86.00  87.0
2018-06-01      2.0  44.0   2.828427  42.0  43.00  44.0  45.00  46.0

PANDAS SERIES AND DATAFRAMES

In [3]:
import pandas as pd
from pandas import Series,DataFrame

In [8]:
obj=Series([4,5,6,-7])
print(obj)
print(obj.index)
print(obj.values)
print("value ",obj[1])

0    4
1    5
2    6
3   -7
dtype: int64
RangeIndex(start=0, stop=4, step=1)
[ 4  5  6 -7]
value  5


In [24]:
obj1=Series([4,5,6,7],index=["a","b","c","d"])
print(obj1)
print(obj1.values)
print(obj1.index)
print("val at index a",obj1["a"])
#change value
obj1["b"]=10
print("after changing")
print(obj1)
print("last 2")
print(obj1[2:])
print(obj1.a)

a    4
b    5
c    6
d    7
dtype: int64
[4 5 6 7]
Index(['a', 'b', 'c', 'd'], dtype='object')
val at index a 4
after changing
a     4
b    10
c     6
d     7
dtype: int64
last 2
c    6
d    7
dtype: int64
4


In [35]:
import numpy as np
obj2=Series({"a":"10","b":20,"c":30})
print(obj2)
# obj3=obj2[obj2>10]
# print(obj3)
# print(obj2**2)
print("b" in obj2)
#boolean

a    10
b    20
c    30
dtype: object
True


In [52]:
#seies from dictionary
sdata={"texas":10,"ohio":20,"ny":30,"califonia":40}
states=["texas","ohio","ny","califonia","utah"]
obj4=Series(sdata,index=states)
print(obj4)
print(obj4["texas"])
print(obj4.values)
print(obj4.texas)
print()
print()
print(pd.isnull(obj4))
print()
print(pd.notnull(obj4))
print()
print(obj4[obj4.notnull()])

texas        10.0
ohio         20.0
ny           30.0
califonia    40.0
utah          NaN
dtype: float64
10.0
[10. 20. 30. 40. nan]
10.0


texas        False
ohio         False
ny           False
califonia    False
utah          True
dtype: bool

texas         True
ohio          True
ny            True
califonia     True
utah         False
dtype: bool

texas        10.0
ohio         20.0
ny           30.0
califonia    40.0
dtype: float64


In [56]:
print(obj4)
ts={"mexico":100,"sdo":200}
ti=["mexico","sdo"]
obj5=Series(ts,index=ti)
print(obj4.add(obj5))

texas        10.0
ohio         20.0
ny           30.0
califonia    40.0
utah          NaN
dtype: float64
califonia   NaN
mexico      NaN
ny          NaN
ohio        NaN
sdo         NaN
texas       NaN
utah        NaN
dtype: float64


In [79]:
print(obj4)
obj4.name="population"
obj4.index.name="STATE"
print()
print(obj4)

STATE
texas        10.0
ohio         20.0
ny           30.0
califonia    40.0
utah          NaN
Name: population, dtype: float64

STATE
texas        10.0
ohio         20.0
ny           30.0
califonia    40.0
utah          NaN
Name: population, dtype: float64


In [62]:
print(obj4.index[2])
print(obj4[2])

ny
30.0


In [77]:
S=Series(range(4),index=["zero","one","two","three"])
print(S)
print()
print("2=",S["two"])
print()
print(S[["zero","three"]])
print(S[[0,2]])
print()
print(S[:-2])
print()
print(S[:2])
print()
print(S[2:])
print()
print(S[-2:])

zero     0
one      1
two      2
three    3
dtype: int64

2= 2

zero     0
three    3
dtype: int64
zero    0
two     2
dtype: int64

zero    0
one     1
dtype: int64

zero    0
one     1
dtype: int64

two      2
three    3
dtype: int64

two      2
three    3
dtype: int64


In [88]:
import random
num = random.random()
print(num)
print("A random number from list is : ", end="")
print(random.choice([1, 4, 8, 10, 3]))

0.1820891322320407
A random number from list is : 8


DATAFRAME

In [205]:
data={"city":["bangalore","chennai","mumbai","delhi"],
     "year":[2000,2001,2002,2003],
     "population":[1000,2000,3000,4000]}
frame=DataFrame(data)
print(frame)

        city  year  population
0  bangalore  2000        1000
1    chennai  2001        2000
2     mumbai  2002        3000
3      delhi  2003        4000


In [208]:
frame2=DataFrame(data,columns=["year","city","population","debt"],index=data["year"])

In [209]:
frame2

year       city  population debt
2000  2000  bangalore        1000  NaN
2001  2001    chennai        2000  NaN
2002  2002     mumbai        3000  NaN
2003  2003      delhi        4000  NaN

In [99]:
#nested dictionaries
pop={"nevada":{2000:2.9,2002:3.0},"Ohio":{300:2.9,502:3.0}}
frame3=DataFrame(pop)
print(frame3)
frame3.index.name="year"
frame3.columns.name="state"
frame3

      nevada  Ohio
2000     2.9   NaN
2002     3.0   NaN
300      NaN   2.9
502      NaN   3.0


state  nevada  Ohio
year               
2000      2.9   NaN
2002      3.0   NaN
300       NaN   2.9
502       NaN   3.0

In [102]:
print(frame3.index)
print(frame3.columns)
print(frame3.values)

Index([2000, 2002, 300, 502], dtype='int64', name='year')
Index(['nevada', 'Ohio'], dtype='object', name='state')
[[2.9 nan]
 [3.  nan]
 [nan 2.9]
 [nan 3. ]]


In [106]:
print(frame.city)
print()
print(frame["population"])

0    bangalore
1      chennai
2       mumbai
3        delhi
Name: city, dtype: object

0    1000
1    2000
2    3000
3    4000
Name: population, dtype: int64


In [107]:
frame2

year       city  population debt
A  2000  bangalore        1000  NaN
B  2001    chennai        2000  NaN
C  2002     mumbai        3000  NaN
D  2003      delhi        4000  NaN

In [109]:
#rows
frame2.loc[["A","B"]]

year       city  population debt
A  2000  bangalore        1000  NaN
B  2001    chennai        2000  NaN

In [110]:
frame2.loc["A"]

year               2000
city          bangalore
population         1000
debt                NaN
Name: A, dtype: object

In [112]:
frame2.loc["A":"C",['city',"year"]]

city  year
A  bangalore  2000
B    chennai  2001
C     mumbai  2002

In [113]:
print(frame2.iloc[1:3])

   year     city  population debt
B  2001  chennai        2000  NaN
C  2002   mumbai        3000  NaN


In [114]:
print(frame2.iloc[:,1:3])

        city  population
A  bangalore        1000
B    chennai        2000
C     mumbai        3000
D      delhi        4000


In [116]:
frame2

year       city  population debt
A  2000  bangalore        1000  NaN
B  2001    chennai        2000  NaN
C  2002     mumbai        3000  NaN
D  2003      delhi        4000  NaN

In [117]:
frame2["debt"]=0

In [118]:
frame2

year       city  population  debt
A  2000  bangalore        1000     0
B  2001    chennai        2000     0
C  2002     mumbai        3000     0
D  2003      delhi        4000     0

In [120]:
val=Series([10,10,10],index=["A","B","C"])

In [121]:
frame2.debt=val

In [122]:
frame2

year       city  population  debt
A  2000  bangalore        1000  10.0
B  2001    chennai        2000  10.0
C  2002     mumbai        3000  10.0
D  2003      delhi        4000   NaN

In [124]:
frame2.debt=range(4)

In [125]:
frame2

year       city  population  debt
A  2000  bangalore        1000     0
B  2001    chennai        2000     1
C  2002     mumbai        3000     2
D  2003      delhi        4000     3

In [126]:
del frame2["debt"]

In [127]:
frame2

year       city  population
A  2000  bangalore        1000
B  2001    chennai        2000
C  2002     mumbai        3000
D  2003      delhi        4000

In [129]:
import numpy as np
dat=np.arange(9).reshape(3,3)
print(dat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [130]:
frame4=DataFrame(dat,index=["r1","r2","r3"],columns=["c1","c2","c3"])

In [131]:
frame4

c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8

In [132]:
frame4.c1

r1    0
r2    3
r3    6
Name: c1, dtype: int32

In [134]:
print(frame4["c2"])

r1    1
r2    4
r3    7
Name: c2, dtype: int32


In [135]:
print(frame4.loc["r1"])

c1    0
c2    1
c3    2
Name: r1, dtype: int32


In [140]:
print(frame4["c2"]["r1"])

1


In [142]:
print(frame4.loc[["r1","r3"]])

    c1  c2  c3
r1   0   1   2
r3   6   7   8


In [143]:
frame4.iloc[:2]

c1  c2  c3
r1   0   1   2
r2   3   4   5

In [144]:
frame4.iloc[:-2]

c1  c2  c3
r1   0   1   2

In [146]:
frame4.iloc[-2:]

c1  c2  c3
r2   3   4   5
r3   6   7   8

In [149]:
print(frame4<3)

       c1     c2     c3
r1   True   True   True
r2  False  False  False
r3  False  False  False


In [151]:
print(frame4["c1"]<3)

r1     True
r2    False
r3    False
Name: c1, dtype: bool


In [152]:
#removing rows
print(frame4)

    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8


In [153]:
print(frame4.drop(["r1"]))

    c1  c2  c3
r2   3   4   5
r3   6   7   8


In [154]:
print(frame4.drop(["r1","r3"]))

    c1  c2  c3
r2   3   4   5


In [155]:
print(frame4.drop(["c1"],axis=1))

    c2  c3
r1   1   2
r2   4   5
r3   7   8


In [156]:
print(frame4.sort_values(by="c1"))

    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8


In [158]:
print(frame4.sort_index())

    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8


In [160]:
frame.describe()

year   population
count     4.000000     4.000000
mean   2001.500000  2500.000000
std       1.290994  1290.994449
min    2000.000000  1000.000000
25%    2000.750000  1750.000000
50%    2001.500000  2500.000000
75%    2002.250000  3250.000000
max    2003.000000  4000.000000

In [161]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   city        4 non-null      object
 1   year        4 non-null      int64 
 2   population  4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes


In [162]:
frame

city  year  population
0  bangalore  2000        1000
1    chennai  2001        2000
2     mumbai  2002        3000
3      delhi  2003        4000

In [164]:
frame6=DataFrame(data,columns=["year","city","population","debt"],index=["A","B","C","D"])

In [165]:
frame6

year       city  population debt
A  2000  bangalore        1000  NaN
B  2001    chennai        2000  NaN
C  2002     mumbai        3000  NaN
D  2003      delhi        4000  NaN

In [178]:
from numpy import nan as NaN
data1=Series([1,NaN,2,NaN])

In [169]:
data1

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [171]:
data1.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [173]:
data1.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [174]:
print(data1.dropna())

0    1.0
2    2.0
dtype: float64


In [175]:
data1.fillna(0)

0    1.0
1    0.0
2    2.0
3    0.0
dtype: float64

In [177]:
data1.fillna(data1.mean(skipna=True))

0    1.0
1    1.5
2    2.0
3    1.5
dtype: float64

In [179]:
data1.fillna(data1.sum(skipna=True))

0    1.0
1    3.0
2    2.0
3    3.0
dtype: float64

In [181]:
data1.sum(skipna=True)

3.0

In [182]:
data1.mean()


1.5

In [183]:
from datetime import datetime

In [184]:
date=pd.to_datetime("13 October 2002")

In [186]:
date

Timestamp('2002-10-13 00:00:00')

In [191]:
date.strftime('%A')

'Sunday'

In [192]:
date.strftime("%a")

'Sun'

In [193]:
date.strftime("%B")

'October'

In [194]:
date.strftime("%b")

'Oct'

In [197]:
date.strftime("%m")

'10'

In [198]:
date.strftime("%S")

'00'

In [199]:
date.strftime("%M")

'00'

In [200]:
date.strftime("%u")

'7'

In [201]:
date.strftime("%D")

'10/13/02'

In [203]:
pd.to_datetime(date,format='%Y-%m-%d')

Timestamp('2002-10-13 00:00:00')